name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"  # Указываем версию в кавычках, чтобы избежать ошибки с 3.1
    steps:
      - uses: actions/checkout@v3

      - name: Debug matrix
        run: |
          echo "Matrix version: ${{ matrix.python-version }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # make зависит от poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
